package org.tensorflow.lite.examples.classification;

public class Utils {

    //Add elements to ingredientlist and imageResouceIdList


    public static String[] ingredientList = {

            "aceituna",
            "acelga",
            "apio",
            "banana",
            "batata",
            "cebolla",
            "coco",
            "coll de brusela",
            "frutilla",
            "mango",
            "manzana roja",
            "manzana verde",
            "maracuya",
            "melon",
            "membrillo",
            "mora",
            "morron rojo",
            "naranja",
            "nuez",
            "palta",
            "pepino",
            "pera",
            "perejil",
            "pomelo",
            "puerro",
            "rabanito",
            "rabano",
            "remolacha",
            "repollo",
            "sandia",
            "tomate",
            "tomate cherry",
            "uva",
            "zanahoria",
            "zapallito",
            "zapallo"


    };

    public static int[] imageResouceIdSuggestedRecipesList = {
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli,
            R.drawable.recetassugeridasbrocoli

    };

    public static int[] imageResouceIdSelectionList = {
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli,
            R.drawable.seleccionsopadebrocoli

    };

    public static int[] imageResouceIdNuticionalInfoList = {
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli,
            R.drawable.informacionnutricionalsopadebrocoli

    };


}
